# frozen_string_literal: true

require 'yaml'
require 'securerandom'
require 'time'
require 'fileutils'

module Vibe
  # Skill generator from analyzed patterns
  class SkillGenerator
    attr_reader :output_dir, :templates

    def initialize(output_dir: nil)
      @output_dir = output_dir || File.expand_path('~/.claude/skills/personal')
      @templates = load_templates
      FileUtils.mkdir_p(@output_dir)
    end

    def default_templates
      {
        skill: <<~TEMPLATE
          ---
          name: %<name>s
          description: %<description>s
          version: 1.0.0
          generated: true
          source:
            sessions: %<session_count>s
            pattern_score: %<confidence>s
            created_at: %<timestamp>s
          tags: %<tags>s
          ---

          # %<title>s

          > **Generated from your successful workflows**
          > Confidence: %<confidence>s | Occurrences: %<occurrences>s | Success Rate: %<success_rate>s%

          ## When to Use

          %<when_to_use>s

          ## Steps

          %<steps>s

          ## Examples

          %<examples>s

          ## Customization

          This skill was auto-generated. Edit to:
          - Add more context
          - Refine steps
          - Add edge cases

          ---
          *Generated by skill-craft on %<date>s*
        TEMPLATE
      }
    end

    def load_templates
      default_templates
    end

    # Generate a skill from a detected pattern
    def generate(pattern, options = {})
      skill_name = generate_skill_name(pattern)
      skill_dir = File.join(@output_dir, skill_name)
      skill_file = File.join(skill_dir, 'SKILL.md')

      if File.exist?(skill_file) && !options[:force]
        return {
          success: false,
          skill_name: skill_name,
          skill_path: skill_file,
          error: :exists,
          message: "Skill '#{skill_name}' already exists at #{skill_file}. " \
                   'Pass force: true to overwrite.'
        }
      end

      FileUtils.mkdir_p(skill_dir)

      content = render_skill_template(pattern, skill_name, options)

      File.write(skill_file, content)

      {
        success: true,
        skill_name: skill_name,
        skill_path: skill_file,
        content: content
      }
    end

    # Preview skill without saving
    def preview(pattern, options = {})
      skill_name = generate_skill_name(pattern)
      content = render_skill_template(pattern, skill_name, options)

      {
        skill_name: skill_name,
        content: content
      }
    end

    # Generate multiple skills from patterns
    def generate_batch(patterns, options = {})
      results = []

      patterns.each do |pattern|
        result = generate(pattern, options)
        results << result
      end

      results
    end

    private

    def generate_skill_name(pattern)
      base_name = case pattern[:type]
                  when :tool_sequence
                    generate_sequence_name(pattern[:pattern])
                  when :error_recovery
                    "error-recovery-#{SecureRandom.hex(4)}"
                  when :workflow
                    pattern[:pattern].downcase.gsub(/\s+/, '-')
                  when :checklist
                    generate_checklist_name(pattern[:pattern])
                  else
                    "custom-skill-#{SecureRandom.hex(4)}"
                  end

      sanitize_name(base_name)
    end

    def generate_sequence_name(sequence)
      tools = sequence.split(' → ').map(&:downcase)
      if tools.size > 2
        "#{tools.first}-to-#{tools.last}-workflow"
      else
        tools.join('-')
      end
    end

    def generate_checklist_name(pattern)
      words = pattern.downcase.gsub(/[^a-z\s]/, '').split.take(4)
      words.join('-')
    end

    def sanitize_name(name)
      name.gsub(/[^a-z0-9-]/, '-').gsub(/-+/, '-').gsub(/^-|-$/, '')
    end

    def render_skill_template(pattern, skill_name, options)
      template = @templates[:skill]

      title = format_title(skill_name)
      description = generate_description(pattern)
      when_to_use = generate_when_to_use(pattern)
      steps = generate_steps(pattern)
      examples = generate_examples(pattern, options)

      format(
        template,
        name: skill_name,
        title: title,
        description: description,
        session_count: pattern[:source_sessions]&.size || 1,
        confidence: pattern[:confidence],
        occurrences: pattern[:occurrences],
        success_rate: (pattern[:success_rate] * 100).round(0),
        timestamp: Time.now.iso8601,
        date: Date.today.to_s,
        tags: (pattern[:tags] || []).inspect,
        when_to_use: when_to_use,
        steps: steps,
        examples: examples
      )
    end

    def format_title(skill_name)
      skill_name.split('-').map(&:capitalize).join(' ')
    end

    def generate_description(pattern)
      case pattern[:type]
      when :tool_sequence
        "Workflow: #{pattern[:pattern]}"
      when :error_recovery
        'Error recovery pattern for common failures'
      when :workflow
        "#{pattern[:pattern].capitalize} workflow with best practices"
      when :checklist
        "Checklist: #{pattern[:pattern]}"
      else
        'Custom skill pattern'
      end
    end

    def generate_when_to_use(pattern)
      case pattern[:type]
      when :tool_sequence
        <<~TEXT
          Use this workflow when:
          - Working with #{pattern[:tags]&.join(' or ')} tasks
          - Need to execute a reliable sequence of operations
          - Following established best practices
        TEXT
      when :error_recovery
        <<~TEXT
          Use this pattern when:
          - Encountering similar errors
          - Need to recover from failures gracefully
          - Following proven recovery procedures
        TEXT
      when :workflow
        <<~TEXT
          Use this workflow when:
          - Starting a #{pattern[:pattern]} task
          - Need structured approach to #{pattern[:pattern]}
          - Following established process
        TEXT
      when :checklist
        <<~TEXT
          Use this checklist when:
          - Need to ensure completeness
          - Following mandatory steps
          - Quality assurance
        TEXT
      else
        'Use when the pattern context applies.'
      end
    end

    def generate_steps(pattern)
      case pattern[:type]
      when :tool_sequence
        generate_sequence_steps(pattern[:pattern])
      when :error_recovery
        generate_recovery_steps(pattern)
      when :workflow
        generate_workflow_steps(pattern[:pattern])
      when :checklist
        generate_checklist_steps(pattern[:pattern])
      else
        '1. Follow the pattern as detected'
      end
    end

    def generate_sequence_steps(sequence)
      tools = sequence.split(' → ')
      steps = tools.each_with_index.map do |tool, i|
        "#{i + 1}. Run **#{tool}** command\n" \
          "   - Command: `[actual command]`\n" \
          '   - Expected: [what to look for]'
      end
      steps.join("\n\n")
    end

    def generate_recovery_steps(pattern)
      steps = [
        '1. **Identify the error**',
        '   - Recognize the error type',
        '   - Check error message patterns',
        '',
        '2. **Apply recovery sequence**',
        "   - Follow: #{pattern[:pattern].split(' → ').drop(1).join(' → ')}",
        '',
        '3. **Verify recovery**',
        '   - Confirm the issue is resolved',
        '   - Check for side effects'
      ]
      steps.join("\n")
    end

    def generate_workflow_steps(workflow_name)
      case workflow_name.downcase
      when 'pre-commit'
        <<~STEPS
          1. **Run linter**
             - Command: `lint` or appropriate linter for project
             - Fix any issues found

          2. **Run tests**
             - Command: `test` or `npm test` or `pytest`
             - Ensure all tests pass

          3. **Commit changes**
             - Write clear commit message
             - Reference related issues
        STEPS
      when 'feature-implementation'
        <<~STEPS
          1. **Plan the feature**
             - Define requirements
             - Design approach

          2. **Implement**
             - Write code
             - Follow project conventions

          3. **Test**
             - Write/update tests
             - Verify functionality
        STEPS
      else
        "1. Follow the #{workflow_name} workflow steps"
      end
    end

    def generate_checklist_steps(pattern)
      items = pattern.split(/[,.]/).reject(&:empty?)
      items.each_with_index.map do |item, i|
        "#{i + 1}. #{item.strip}"
      end.join("\n")
    end

    def generate_examples(pattern, _options)
      examples = []

      # Add example from pattern data
      if pattern[:examples]&.any?
        pattern[:examples].first(3).each_with_index do |example, i|
          examples << "### Example #{i + 1}\n```\n#{example}\n```"
        end
      end

      # Add generated example if none exist
      if examples.empty?
        examples << <<~EXAMPLE
          ### Example Scenario
          ```
          # Context: #{pattern[:type]} pattern detected
          # Pattern: #{pattern[:pattern]}
          # Apply this skill when the context matches
          ```
        EXAMPLE
      end

      examples.join("\n\n")
    end
  end
end
