# frozen_string_literal: true

require 'minitest/autorun'
require_relative '../../lib/vibe/doc_rendering'
require_relative '../../lib/vibe/external_tools'
require_relative '../../lib/vibe/utils'
require_relative '../../lib/vibe/overlay_support'

# Test host class that includes all required modules
class DocRenderingTestHost
  include Vibe::DocRendering
  include Vibe::ExternalTools
  include Vibe::Utils
  include Vibe::OverlaySupport

  attr_accessor :repo_root, :skip_integrations, :target_platform

  def initialize(repo_root)
    @repo_root = repo_root
  end

  # Stub providers for testing
  def providers
    {}
  end
end

class TestDocRenderingTools < Minitest::Test
  def setup
    @repo_root = File.expand_path('../../', __dir__)
    @host = DocRenderingTestHost.new(@repo_root)
  end

  def test_render_tools_doc_returns_string
    manifest = { 'target' => 'claude-code' }
    result = @host.render_tools_doc(manifest)
    assert result.is_a?(String)
    assert result.include?('# Available CLI Tools')
  end

  def test_render_tools_doc_includes_categories
    manifest = { 'target' => 'claude-code' }
    result = @host.render_tools_doc(manifest)
    assert result.include?('## File Operations')
    assert result.include?('## Text Search')
    assert result.include?('## System Monitoring')
  end

  def test_render_tools_doc_includes_fallback_strategy
    manifest = { 'target' => 'claude-code' }
    result = @host.render_tools_doc(manifest)
    assert result.include?('## Fallback Strategy')
    assert result.include?('vibe doctor')
  end

  def test_render_tools_doc_includes_recommendation
    manifest = { 'target' => 'claude-code' }
    result = @host.render_tools_doc(manifest)
    assert result.include?('## Recommendation')
    assert result.include?('Prefer modern tools')
  end

  def test_render_tools_doc_shows_status_icons
    manifest = { 'target' => 'claude-code' }
    result = @host.render_tools_doc(manifest)
    # Should have at least one status icon
    assert(result.include?('✅') || result.include?('❌'),
           'Should show status icons for tools')
  end

  def test_render_tools_doc_lists_all_tools
    manifest = { 'target' => 'claude-code' }
    result = @host.render_tools_doc(manifest)

    # All 8 tools should be mentioned
    tools = %w[bat fd rg eza dust duf procs btop]
    tools.each do |tool|
      assert result.include?("`#{tool}`"), "Should mention #{tool}"
    end
  end

  def test_render_tools_doc_includes_traditional_equivalents
    manifest = { 'target' => 'claude-code' }
    result = @host.render_tools_doc(manifest)

    # Traditional tools should be mentioned
    traditional = %w[cat find grep ls du df ps top]
    traditional.each do |tool|
      assert result.include?("`#{tool}`"), "Should mention traditional tool #{tool}"
    end
  end

  def test_render_tools_doc_includes_timestamp
    manifest = { 'target' => 'claude-code' }
    result = @host.render_tools_doc(manifest)
    assert result.include?('Last updated:')
    assert result.include?('Generated by: vibe doctor')
  end

  def test_render_tools_doc_handles_empty_tools_gracefully
    # This tests that the method doesn't crash if somehow no tools are defined
    manifest = { 'target' => 'claude-code' }
    result = @host.render_tools_doc(manifest)
    # Should still return a valid markdown document
    assert result.start_with?('# Available CLI Tools')
  end
end
